// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/application.proto

package ttnpb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	go_thethings_network_lorawan_stack_v3_pkg_types "go.thethings.network/lorawan-stack/v3/pkg/types"
	math "math"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Application is the message that defines an Application in the network.
type Application struct {
	// The identifiers of the application. These are public and can be seen by any authenticated user in the network.
	Ids *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	// When the application was created. This information is public and can be seen by any authenticated user in the network.
	CreatedAt time.Time `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// When the application was last updated. This information is public and can be seen by any authenticated user in the network.
	UpdatedAt time.Time `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	// When the application was deleted. This information is public and can be seen by any authenticated user in the network.
	DeletedAt *time.Time `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3,stdtime" json:"deleted_at,omitempty"`
	// The name of the application.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// A description for the application.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Key-value attributes for this application. Typically used for organizing applications or for storing integration-specific data.
	Attributes map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Contact information for this application. Typically used to indicate who to contact with technical/security questions about the application.
	ContactInfo          []*ContactInfo `protobuf:"bytes,7,rep,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	DevEuiCounter        uint32         `protobuf:"varint,9,opt,name=dev_eui_counter,json=devEuiCounter,proto3" json:"dev_eui_counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Application) Reset()      { *m = Application{} }
func (*Application) ProtoMessage() {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{0}
}
func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetIds() *ApplicationIdentifiers {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Application) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Application) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *Application) GetDeletedAt() *time.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Application) GetContactInfo() []*ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Application) GetDevEuiCounter() uint32 {
	if m != nil {
		return m.DevEuiCounter
	}
	return 0
}

type Applications struct {
	Applications         []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Applications) Reset()      { *m = Applications{} }
func (*Applications) ProtoMessage() {}
func (*Applications) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{1}
}
func (m *Applications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Applications.Unmarshal(m, b)
}
func (m *Applications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Applications.Marshal(b, m, deterministic)
}
func (m *Applications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Applications.Merge(m, src)
}
func (m *Applications) XXX_Size() int {
	return xxx_messageInfo_Applications.Size(m)
}
func (m *Applications) XXX_DiscardUnknown() {
	xxx_messageInfo_Applications.DiscardUnknown(m)
}

var xxx_messageInfo_Applications proto.InternalMessageInfo

func (m *Applications) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type IssueDevEUIResponse struct {
	DevEui               go_thethings_network_lorawan_stack_v3_pkg_types.EUI64 `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3,customtype=go.thethings.network/lorawan-stack/v3/pkg/types.EUI64" json:"dev_eui"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *IssueDevEUIResponse) Reset()      { *m = IssueDevEUIResponse{} }
func (*IssueDevEUIResponse) ProtoMessage() {}
func (*IssueDevEUIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{2}
}
func (m *IssueDevEUIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueDevEUIResponse.Unmarshal(m, b)
}
func (m *IssueDevEUIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueDevEUIResponse.Marshal(b, m, deterministic)
}
func (m *IssueDevEUIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueDevEUIResponse.Merge(m, src)
}
func (m *IssueDevEUIResponse) XXX_Size() int {
	return xxx_messageInfo_IssueDevEUIResponse.Size(m)
}
func (m *IssueDevEUIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueDevEUIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssueDevEUIResponse proto.InternalMessageInfo

type GetApplicationRequest struct {
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	// The names of the application fields that should be returned.
	FieldMask            *types.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetApplicationRequest) Reset()      { *m = GetApplicationRequest{} }
func (*GetApplicationRequest) ProtoMessage() {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{3}
}
func (m *GetApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationRequest.Unmarshal(m, b)
}
func (m *GetApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationRequest.Merge(m, src)
}
func (m *GetApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationRequest.Size(m)
}
func (m *GetApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationRequest proto.InternalMessageInfo

func (m *GetApplicationRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *GetApplicationRequest) GetFieldMask() *types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type ListApplicationsRequest struct {
	// By default we list all applications the caller has rights on.
	// Set the user or the organization (not both) to instead list the applications
	// where the user or organization is collaborator on.
	Collaborator *OrganizationOrUserIdentifiers `protobuf:"bytes,1,opt,name=collaborator,proto3" json:"collaborator,omitempty"`
	// The names of the application fields that should be returned.
	FieldMask *types.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Order the results by this field path (must be present in the field mask).
	// Default ordering is by ID. Prepend with a minus (-) to reverse the order.
	Order string `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	// Limit the number of results per page.
	Limit uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page number for pagination. 0 is interpreted as 1.
	Page uint32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	// Only return recently deleted applications.
	Deleted              bool     `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationsRequest) Reset()      { *m = ListApplicationsRequest{} }
func (*ListApplicationsRequest) ProtoMessage() {}
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{4}
}
func (m *ListApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsRequest.Unmarshal(m, b)
}
func (m *ListApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsRequest.Merge(m, src)
}
func (m *ListApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsRequest.Size(m)
}
func (m *ListApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsRequest proto.InternalMessageInfo

func (m *ListApplicationsRequest) GetCollaborator() *OrganizationOrUserIdentifiers {
	if m != nil {
		return m.Collaborator
	}
	return nil
}

func (m *ListApplicationsRequest) GetFieldMask() *types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListApplicationsRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *ListApplicationsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListApplicationsRequest) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type CreateApplicationRequest struct {
	Application `protobuf:"bytes,1,opt,name=application,proto3,embedded=application" json:"application"`
	// Collaborator to grant all rights on the newly created application.
	Collaborator         OrganizationOrUserIdentifiers `protobuf:"bytes,2,opt,name=collaborator,proto3" json:"collaborator"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateApplicationRequest) Reset()      { *m = CreateApplicationRequest{} }
func (*CreateApplicationRequest) ProtoMessage() {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{5}
}
func (m *CreateApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationRequest.Unmarshal(m, b)
}
func (m *CreateApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationRequest.Merge(m, src)
}
func (m *CreateApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationRequest.Size(m)
}
func (m *CreateApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationRequest proto.InternalMessageInfo

func (m *CreateApplicationRequest) GetCollaborator() OrganizationOrUserIdentifiers {
	if m != nil {
		return m.Collaborator
	}
	return OrganizationOrUserIdentifiers{}
}

type UpdateApplicationRequest struct {
	Application `protobuf:"bytes,1,opt,name=application,proto3,embedded=application" json:"application"`
	// The names of the application fields that should be updated.
	FieldMask            *types.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateApplicationRequest) Reset()      { *m = UpdateApplicationRequest{} }
func (*UpdateApplicationRequest) ProtoMessage() {}
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{6}
}
func (m *UpdateApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateApplicationRequest.Unmarshal(m, b)
}
func (m *UpdateApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateApplicationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateApplicationRequest.Merge(m, src)
}
func (m *UpdateApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateApplicationRequest.Size(m)
}
func (m *UpdateApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateApplicationRequest proto.InternalMessageInfo

func (m *UpdateApplicationRequest) GetFieldMask() *types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type ListApplicationAPIKeysRequest struct {
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	// Limit the number of results per page.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page number for pagination. 0 is interpreted as 1.
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationAPIKeysRequest) Reset()      { *m = ListApplicationAPIKeysRequest{} }
func (*ListApplicationAPIKeysRequest) ProtoMessage() {}
func (*ListApplicationAPIKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{7}
}
func (m *ListApplicationAPIKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationAPIKeysRequest.Unmarshal(m, b)
}
func (m *ListApplicationAPIKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationAPIKeysRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationAPIKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationAPIKeysRequest.Merge(m, src)
}
func (m *ListApplicationAPIKeysRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationAPIKeysRequest.Size(m)
}
func (m *ListApplicationAPIKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationAPIKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationAPIKeysRequest proto.InternalMessageInfo

func (m *ListApplicationAPIKeysRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *ListApplicationAPIKeysRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationAPIKeysRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetApplicationAPIKeyRequest struct {
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	// Unique public identifier for the API key.
	KeyId                string   `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationAPIKeyRequest) Reset()      { *m = GetApplicationAPIKeyRequest{} }
func (*GetApplicationAPIKeyRequest) ProtoMessage() {}
func (*GetApplicationAPIKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{8}
}
func (m *GetApplicationAPIKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationAPIKeyRequest.Unmarshal(m, b)
}
func (m *GetApplicationAPIKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationAPIKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationAPIKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationAPIKeyRequest.Merge(m, src)
}
func (m *GetApplicationAPIKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationAPIKeyRequest.Size(m)
}
func (m *GetApplicationAPIKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationAPIKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationAPIKeyRequest proto.InternalMessageInfo

func (m *GetApplicationAPIKeyRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *GetApplicationAPIKeyRequest) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

type CreateApplicationAPIKeyRequest struct {
	ApplicationIds       *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	Name                 string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rights               []Right                 `protobuf:"varint,3,rep,packed,name=rights,proto3,enum=ttn.lorawan.v3.Right" json:"rights,omitempty"`
	ExpiresAt            *time.Time              `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,stdtime" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateApplicationAPIKeyRequest) Reset()      { *m = CreateApplicationAPIKeyRequest{} }
func (*CreateApplicationAPIKeyRequest) ProtoMessage() {}
func (*CreateApplicationAPIKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{9}
}
func (m *CreateApplicationAPIKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationAPIKeyRequest.Unmarshal(m, b)
}
func (m *CreateApplicationAPIKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationAPIKeyRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationAPIKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationAPIKeyRequest.Merge(m, src)
}
func (m *CreateApplicationAPIKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationAPIKeyRequest.Size(m)
}
func (m *CreateApplicationAPIKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationAPIKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationAPIKeyRequest proto.InternalMessageInfo

func (m *CreateApplicationAPIKeyRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *CreateApplicationAPIKeyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateApplicationAPIKeyRequest) GetRights() []Right {
	if m != nil {
		return m.Rights
	}
	return nil
}

func (m *CreateApplicationAPIKeyRequest) GetExpiresAt() *time.Time {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type UpdateApplicationAPIKeyRequest struct {
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	APIKey         `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3,embedded=api_key" json:"api_key"`
	// The names of the api key fields that should be updated.
	FieldMask            *types.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateApplicationAPIKeyRequest) Reset()      { *m = UpdateApplicationAPIKeyRequest{} }
func (*UpdateApplicationAPIKeyRequest) ProtoMessage() {}
func (*UpdateApplicationAPIKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{10}
}
func (m *UpdateApplicationAPIKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateApplicationAPIKeyRequest.Unmarshal(m, b)
}
func (m *UpdateApplicationAPIKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateApplicationAPIKeyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateApplicationAPIKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateApplicationAPIKeyRequest.Merge(m, src)
}
func (m *UpdateApplicationAPIKeyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateApplicationAPIKeyRequest.Size(m)
}
func (m *UpdateApplicationAPIKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateApplicationAPIKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateApplicationAPIKeyRequest proto.InternalMessageInfo

func (m *UpdateApplicationAPIKeyRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *UpdateApplicationAPIKeyRequest) GetFieldMask() *types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type ListApplicationCollaboratorsRequest struct {
	ApplicationIds *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	// Limit the number of results per page.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page number for pagination. 0 is interpreted as 1.
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplicationCollaboratorsRequest) Reset()      { *m = ListApplicationCollaboratorsRequest{} }
func (*ListApplicationCollaboratorsRequest) ProtoMessage() {}
func (*ListApplicationCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{11}
}
func (m *ListApplicationCollaboratorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationCollaboratorsRequest.Unmarshal(m, b)
}
func (m *ListApplicationCollaboratorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationCollaboratorsRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationCollaboratorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationCollaboratorsRequest.Merge(m, src)
}
func (m *ListApplicationCollaboratorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationCollaboratorsRequest.Size(m)
}
func (m *ListApplicationCollaboratorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationCollaboratorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationCollaboratorsRequest proto.InternalMessageInfo

func (m *ListApplicationCollaboratorsRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *ListApplicationCollaboratorsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationCollaboratorsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetApplicationCollaboratorRequest struct {
	ApplicationIds       *ApplicationIdentifiers        `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	Collaborator         *OrganizationOrUserIdentifiers `protobuf:"bytes,2,opt,name=collaborator,proto3" json:"collaborator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetApplicationCollaboratorRequest) Reset()      { *m = GetApplicationCollaboratorRequest{} }
func (*GetApplicationCollaboratorRequest) ProtoMessage() {}
func (*GetApplicationCollaboratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{12}
}
func (m *GetApplicationCollaboratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationCollaboratorRequest.Unmarshal(m, b)
}
func (m *GetApplicationCollaboratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationCollaboratorRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationCollaboratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationCollaboratorRequest.Merge(m, src)
}
func (m *GetApplicationCollaboratorRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationCollaboratorRequest.Size(m)
}
func (m *GetApplicationCollaboratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationCollaboratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationCollaboratorRequest proto.InternalMessageInfo

func (m *GetApplicationCollaboratorRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *GetApplicationCollaboratorRequest) GetCollaborator() *OrganizationOrUserIdentifiers {
	if m != nil {
		return m.Collaborator
	}
	return nil
}

type SetApplicationCollaboratorRequest struct {
	ApplicationIds       *ApplicationIdentifiers `protobuf:"bytes,1,opt,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	Collaborator         *Collaborator           `protobuf:"bytes,2,opt,name=collaborator,proto3" json:"collaborator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SetApplicationCollaboratorRequest) Reset()      { *m = SetApplicationCollaboratorRequest{} }
func (*SetApplicationCollaboratorRequest) ProtoMessage() {}
func (*SetApplicationCollaboratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{13}
}
func (m *SetApplicationCollaboratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetApplicationCollaboratorRequest.Unmarshal(m, b)
}
func (m *SetApplicationCollaboratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetApplicationCollaboratorRequest.Marshal(b, m, deterministic)
}
func (m *SetApplicationCollaboratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetApplicationCollaboratorRequest.Merge(m, src)
}
func (m *SetApplicationCollaboratorRequest) XXX_Size() int {
	return xxx_messageInfo_SetApplicationCollaboratorRequest.Size(m)
}
func (m *SetApplicationCollaboratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetApplicationCollaboratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetApplicationCollaboratorRequest proto.InternalMessageInfo

func (m *SetApplicationCollaboratorRequest) GetApplicationIds() *ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func (m *SetApplicationCollaboratorRequest) GetCollaborator() *Collaborator {
	if m != nil {
		return m.Collaborator
	}
	return nil
}

type ListAllApplicationsResponse struct {
	ApplicationIds       []*ApplicationIdentifiers `protobuf:"bytes,1,rep,name=application_ids,json=applicationIds,proto3" json:"application_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListAllApplicationsResponse) Reset()      { *m = ListAllApplicationsResponse{} }
func (*ListAllApplicationsResponse) ProtoMessage() {}
func (*ListAllApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d90136b1f4f7b1, []int{14}
}
func (m *ListAllApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllApplicationsResponse.Unmarshal(m, b)
}
func (m *ListAllApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *ListAllApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllApplicationsResponse.Merge(m, src)
}
func (m *ListAllApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAllApplicationsResponse.Size(m)
}
func (m *ListAllApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllApplicationsResponse proto.InternalMessageInfo

func (m *ListAllApplicationsResponse) GetApplicationIds() []*ApplicationIdentifiers {
	if m != nil {
		return m.ApplicationIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Application)(nil), "ttn.lorawan.v3.Application")
	golang_proto.RegisterType((*Application)(nil), "ttn.lorawan.v3.Application")
	proto.RegisterMapType((map[string]string)(nil), "ttn.lorawan.v3.Application.AttributesEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "ttn.lorawan.v3.Application.AttributesEntry")
	proto.RegisterType((*Applications)(nil), "ttn.lorawan.v3.Applications")
	golang_proto.RegisterType((*Applications)(nil), "ttn.lorawan.v3.Applications")
	proto.RegisterType((*IssueDevEUIResponse)(nil), "ttn.lorawan.v3.IssueDevEUIResponse")
	golang_proto.RegisterType((*IssueDevEUIResponse)(nil), "ttn.lorawan.v3.IssueDevEUIResponse")
	proto.RegisterType((*GetApplicationRequest)(nil), "ttn.lorawan.v3.GetApplicationRequest")
	golang_proto.RegisterType((*GetApplicationRequest)(nil), "ttn.lorawan.v3.GetApplicationRequest")
	proto.RegisterType((*ListApplicationsRequest)(nil), "ttn.lorawan.v3.ListApplicationsRequest")
	golang_proto.RegisterType((*ListApplicationsRequest)(nil), "ttn.lorawan.v3.ListApplicationsRequest")
	proto.RegisterType((*CreateApplicationRequest)(nil), "ttn.lorawan.v3.CreateApplicationRequest")
	golang_proto.RegisterType((*CreateApplicationRequest)(nil), "ttn.lorawan.v3.CreateApplicationRequest")
	proto.RegisterType((*UpdateApplicationRequest)(nil), "ttn.lorawan.v3.UpdateApplicationRequest")
	golang_proto.RegisterType((*UpdateApplicationRequest)(nil), "ttn.lorawan.v3.UpdateApplicationRequest")
	proto.RegisterType((*ListApplicationAPIKeysRequest)(nil), "ttn.lorawan.v3.ListApplicationAPIKeysRequest")
	golang_proto.RegisterType((*ListApplicationAPIKeysRequest)(nil), "ttn.lorawan.v3.ListApplicationAPIKeysRequest")
	proto.RegisterType((*GetApplicationAPIKeyRequest)(nil), "ttn.lorawan.v3.GetApplicationAPIKeyRequest")
	golang_proto.RegisterType((*GetApplicationAPIKeyRequest)(nil), "ttn.lorawan.v3.GetApplicationAPIKeyRequest")
	proto.RegisterType((*CreateApplicationAPIKeyRequest)(nil), "ttn.lorawan.v3.CreateApplicationAPIKeyRequest")
	golang_proto.RegisterType((*CreateApplicationAPIKeyRequest)(nil), "ttn.lorawan.v3.CreateApplicationAPIKeyRequest")
	proto.RegisterType((*UpdateApplicationAPIKeyRequest)(nil), "ttn.lorawan.v3.UpdateApplicationAPIKeyRequest")
	golang_proto.RegisterType((*UpdateApplicationAPIKeyRequest)(nil), "ttn.lorawan.v3.UpdateApplicationAPIKeyRequest")
	proto.RegisterType((*ListApplicationCollaboratorsRequest)(nil), "ttn.lorawan.v3.ListApplicationCollaboratorsRequest")
	golang_proto.RegisterType((*ListApplicationCollaboratorsRequest)(nil), "ttn.lorawan.v3.ListApplicationCollaboratorsRequest")
	proto.RegisterType((*GetApplicationCollaboratorRequest)(nil), "ttn.lorawan.v3.GetApplicationCollaboratorRequest")
	golang_proto.RegisterType((*GetApplicationCollaboratorRequest)(nil), "ttn.lorawan.v3.GetApplicationCollaboratorRequest")
	proto.RegisterType((*SetApplicationCollaboratorRequest)(nil), "ttn.lorawan.v3.SetApplicationCollaboratorRequest")
	golang_proto.RegisterType((*SetApplicationCollaboratorRequest)(nil), "ttn.lorawan.v3.SetApplicationCollaboratorRequest")
	proto.RegisterType((*ListAllApplicationsResponse)(nil), "ttn.lorawan.v3.ListAllApplicationsResponse")
	golang_proto.RegisterType((*ListAllApplicationsResponse)(nil), "ttn.lorawan.v3.ListAllApplicationsResponse")
}

func init() {
	proto.RegisterFile("lorawan-stack/api/application.proto", fileDescriptor_57d90136b1f4f7b1)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/application.proto", fileDescriptor_57d90136b1f4f7b1)
}

var fileDescriptor_57d90136b1f4f7b1 = []byte{
	// 1204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x8c, 0xdb, 0x44,
	0x14, 0xde, 0x71, 0x7e, 0x76, 0xf3, 0xb2, 0x7f, 0x18, 0x0a, 0xd6, 0x2e, 0x78, 0x53, 0x77, 0x55,
	0x85, 0x42, 0x1c, 0x94, 0x52, 0x44, 0x2b, 0x55, 0xdb, 0x78, 0x59, 0x4a, 0x28, 0xed, 0x82, 0x61,
	0x39, 0x50, 0x95, 0x68, 0x12, 0x4f, 0xbc, 0xa3, 0x38, 0xb6, 0xb1, 0x27, 0x69, 0x53, 0x84, 0x04,
	0x3d, 0x72, 0xaa, 0x7a, 0x41, 0xe2, 0x8a, 0x84, 0x90, 0xb8, 0x21, 0xc1, 0x89, 0x03, 0xc7, 0x1e,
	0x38, 0xf4, 0x84, 0x10, 0x48, 0x8b, 0xd8, 0x5e, 0x2a, 0x71, 0xe1, 0x9c, 0x13, 0xf2, 0xd8, 0x69,
	0x9c, 0x1f, 0xb6, 0x2c, 0xad, 0xa2, 0x9e, 0x32, 0x33, 0x79, 0xef, 0xcd, 0xf7, 0x9e, 0xbf, 0xef,
	0xcd, 0x83, 0x63, 0x96, 0xe3, 0xe1, 0xab, 0xd8, 0x2e, 0xf8, 0x0c, 0xd7, 0x9b, 0x45, 0xec, 0xd2,
	0x22, 0x76, 0x5d, 0x8b, 0xd6, 0x31, 0xa3, 0x8e, 0xad, 0xba, 0x9e, 0xc3, 0x1c, 0x71, 0x91, 0x31,
	0x5b, 0x8d, 0x0c, 0xd5, 0xce, 0xc9, 0x95, 0xb2, 0x49, 0xd9, 0x6e, 0xbb, 0xa6, 0xd6, 0x9d, 0x56,
	0x91, 0xd8, 0x1d, 0xa7, 0xeb, 0x7a, 0xce, 0xb5, 0x6e, 0x91, 0x1b, 0xd7, 0x0b, 0x26, 0xb1, 0x0b,
	0x1d, 0x6c, 0x51, 0x03, 0x33, 0x52, 0x1c, 0x5b, 0x84, 0x21, 0x57, 0x0a, 0xb1, 0x10, 0xa6, 0x63,
	0x3a, 0xa1, 0x73, 0xad, 0xdd, 0xe0, 0x3b, 0xbe, 0xe1, 0xab, 0xc8, 0x3c, 0x67, 0x3a, 0x8e, 0x69,
	0x91, 0x81, 0x55, 0x83, 0x12, 0xcb, 0xa8, 0xb6, 0xb0, 0xdf, 0x8c, 0x2c, 0xd6, 0x46, 0x2d, 0x18,
	0x6d, 0x11, 0x9f, 0xe1, 0x96, 0x1b, 0x19, 0xac, 0x8f, 0x67, 0x5a, 0x77, 0x6c, 0x86, 0xeb, 0xac,
	0x4a, 0xed, 0x46, 0xff, 0xa2, 0x09, 0xf5, 0xa0, 0x06, 0xb1, 0x19, 0x6d, 0x50, 0xe2, 0xf9, 0x91,
	0x91, 0x3c, 0x6e, 0xe4, 0x51, 0x73, 0x97, 0x45, 0xff, 0x2b, 0x5f, 0xa5, 0x20, 0x5b, 0x1e, 0x54,
	0x51, 0x7c, 0x13, 0x12, 0xd4, 0xf0, 0x25, 0x94, 0x43, 0xf9, 0x6c, 0xe9, 0xb8, 0x3a, 0x5c, 0x4d,
	0x35, 0x66, 0x59, 0x19, 0x5c, 0xa5, 0x2d, 0xf7, 0xb4, 0xd4, 0xe7, 0x48, 0x58, 0x46, 0xb7, 0xf7,
	0xd6, 0x66, 0xee, 0xec, 0xad, 0x21, 0x3d, 0x08, 0x22, 0x6e, 0x02, 0xd4, 0x3d, 0x82, 0x19, 0x31,
	0xaa, 0x98, 0x49, 0x02, 0x0f, 0xb9, 0xa2, 0x86, 0xc9, 0xab, 0xfd, 0xe4, 0xd5, 0xf7, 0xfa, 0xc9,
	0x6b, 0x73, 0x81, 0xfb, 0xcd, 0x3f, 0xd6, 0x90, 0x9e, 0x89, 0xfc, 0xca, 0x2c, 0x08, 0xd2, 0x76,
	0x8d, 0x7e, 0x90, 0xc4, 0x61, 0x82, 0x44, 0x7e, 0x65, 0x26, 0x6e, 0x00, 0x18, 0xc4, 0x22, 0x51,
	0x90, 0xb9, 0x07, 0x06, 0x49, 0x86, 0x01, 0x22, 0x9f, 0x32, 0x13, 0x57, 0x21, 0x69, 0xe3, 0x16,
	0x91, 0x92, 0x39, 0x94, 0xcf, 0x68, 0xb3, 0x3d, 0x2d, 0xe9, 0x09, 0x52, 0x49, 0xe7, 0x87, 0xe2,
	0x09, 0xc8, 0x1a, 0xc4, 0xaf, 0x7b, 0xd4, 0x0d, 0x0a, 0x23, 0xa5, 0xb8, 0xcd, 0x5c, 0x4f, 0x4b,
	0x79, 0x09, 0xe9, 0xce, 0x92, 0x1e, 0xff, 0x53, 0xbc, 0x81, 0x00, 0x30, 0x63, 0x1e, 0xad, 0xb5,
	0x19, 0xf1, 0xa5, 0x74, 0x2e, 0x91, 0xcf, 0x96, 0x5e, 0x38, 0xa0, 0xce, 0x6a, 0xf9, 0xbe, 0xf5,
	0x96, 0xcd, 0xbc, 0xae, 0x76, 0xaa, 0xa7, 0x95, 0xbe, 0x44, 0xc5, 0x65, 0x50, 0xd6, 0x3d, 0x45,
	0x5a, 0x2f, 0xc9, 0x1f, 0x5e, 0xc6, 0x85, 0xeb, 0x2f, 0x15, 0x4e, 0x5f, 0xc9, 0x6f, 0x9c, 0xb9,
	0x5c, 0xb8, 0xb2, 0xd1, 0xdf, 0x3e, 0xff, 0x71, 0xe9, 0xc5, 0x4f, 0xd6, 0x4f, 0x04, 0x28, 0x6e,
	0x23, 0x3d, 0x76, 0xab, 0xf8, 0x06, 0xcc, 0xc7, 0xf9, 0x24, 0xcd, 0x72, 0x14, 0xab, 0xa3, 0x28,
	0x36, 0x43, 0x9b, 0x8a, 0xdd, 0x70, 0x78, 0x3a, 0xb7, 0x90, 0xb0, 0x0c, 0x7a, 0xb6, 0x3e, 0x38,
	0x16, 0x8f, 0xc3, 0x92, 0x41, 0x3a, 0x55, 0xd2, 0xa6, 0xd5, 0xba, 0xd3, 0xb6, 0x19, 0xf1, 0xa4,
	0x4c, 0x0e, 0xe5, 0x17, 0xf4, 0x05, 0x83, 0x74, 0xb6, 0xda, 0x74, 0x33, 0x3c, 0x5c, 0x39, 0x0b,
	0x4b, 0x23, 0x79, 0x88, 0xcb, 0x90, 0x68, 0x92, 0x2e, 0x67, 0x5a, 0x46, 0x0f, 0x96, 0xe2, 0x53,
	0x90, 0xea, 0x60, 0xab, 0x4d, 0x38, 0x55, 0x32, 0x7a, 0xb8, 0x39, 0x23, 0xbc, 0x8a, 0x94, 0x6d,
	0x98, 0x8f, 0x95, 0xc4, 0x17, 0x37, 0x60, 0x3e, 0x26, 0xfd, 0x80, 0xae, 0x13, 0x13, 0x88, 0xf9,
	0xe8, 0x43, 0x0e, 0x4a, 0x0b, 0x9e, 0xac, 0xf8, 0x7e, 0x9b, 0xbc, 0x46, 0x3a, 0x5b, 0x3b, 0x15,
	0x9d, 0xf8, 0xae, 0x63, 0xfb, 0x44, 0x7c, 0x1f, 0x66, 0xa3, 0x74, 0x38, 0xae, 0x79, 0xed, 0x6c,
	0xc0, 0xa6, 0xdf, 0xf6, 0xd6, 0x4e, 0x99, 0x8e, 0xca, 0x76, 0x09, 0xdb, 0xa5, 0xb6, 0xe9, 0xab,
	0x36, 0x61, 0x57, 0x1d, 0xaf, 0x59, 0x1c, 0xd6, 0x56, 0xe7, 0x64, 0xd1, 0x6d, 0x9a, 0x45, 0xd6,
	0x75, 0x89, 0xaf, 0x6e, 0xed, 0x54, 0x5e, 0x79, 0x59, 0x4f, 0x87, 0x55, 0x50, 0xbe, 0x47, 0x70,
	0xe4, 0x3c, 0x61, 0x71, 0x3c, 0xe4, 0xa3, 0x36, 0xf1, 0x99, 0x88, 0x61, 0x29, 0x06, 0xac, 0xfa,
	0x28, 0xb4, 0xb7, 0x88, 0xe3, 0x96, 0xbe, 0x78, 0x1a, 0x60, 0xd0, 0x82, 0xfe, 0x55, 0x86, 0xaf,
	0x07, 0x26, 0x17, 0xb1, 0xdf, 0xd4, 0x33, 0x8d, 0xfe, 0x52, 0xf9, 0x5d, 0x80, 0x67, 0xde, 0xa2,
	0x7e, 0x1c, 0xb8, 0xdf, 0x47, 0xfe, 0x4e, 0x40, 0x22, 0xcb, 0xc2, 0x35, 0xc7, 0xc3, 0xcc, 0xf1,
	0x22, 0xd8, 0x85, 0x51, 0xd8, 0xdb, 0x9e, 0x89, 0x6d, 0x7a, 0x9d, 0xfb, 0x6e, 0x7b, 0x3b, 0x3e,
	0xf1, 0x62, 0xe8, 0xf5, 0xa1, 0x10, 0x0f, 0x81, 0x54, 0x34, 0x20, 0xe5, 0x78, 0x06, 0xf1, 0x78,
	0x87, 0xc8, 0x68, 0x97, 0x7a, 0xda, 0x05, 0xaf, 0xa2, 0xcf, 0x0c, 0x15, 0xa3, 0x4a, 0x0d, 0x7d,
	0xa9, 0x30, 0x72, 0xc0, 0x25, 0xac, 0xa7, 0x0a, 0xfc, 0x27, 0xd6, 0xaf, 0xf4, 0x6c, 0x21, 0xb6,
	0x09, 0x83, 0x8b, 0x32, 0xa4, 0x2c, 0xda, 0xa2, 0x8c, 0xf7, 0x81, 0x05, 0x2e, 0x8a, 0x13, 0x09,
	0xe9, 0xde, 0xac, 0x1e, 0x1e, 0x8b, 0x22, 0x24, 0x5d, 0x6c, 0x12, 0xde, 0x02, 0x16, 0x74, 0xbe,
	0x16, 0xa5, 0x80, 0x53, 0xbc, 0x8f, 0x48, 0xe9, 0x1c, 0xca, 0xcf, 0xe9, 0xfd, 0xad, 0xf2, 0x33,
	0x02, 0x69, 0x93, 0xdf, 0x31, 0x81, 0x18, 0xdb, 0x90, 0x8d, 0x21, 0x8d, 0xaa, 0x7b, 0x10, 0xc3,
	0x27, 0x30, 0x21, 0x1e, 0x41, 0xac, 0x8e, 0x7c, 0x2f, 0xe1, 0x7f, 0x7c, 0x2f, 0x6d, 0x3e, 0x7e,
	0xc7, 0xf0, 0xd7, 0x53, 0xbe, 0x46, 0x20, 0xed, 0xf0, 0x96, 0x3b, 0x8d, 0x74, 0x1e, 0x82, 0xd5,
	0x3f, 0x20, 0x78, 0x6e, 0x84, 0xd5, 0xe5, 0xb7, 0x2b, 0x17, 0x48, 0xd7, 0x9f, 0xa2, 0x2a, 0xef,
	0x53, 0x49, 0x38, 0x98, 0x4a, 0x89, 0x01, 0x95, 0x94, 0x2f, 0x10, 0xac, 0x0e, 0xb7, 0x91, 0x10,
	0xf7, 0x14, 0x61, 0x1f, 0x81, 0x74, 0x93, 0x74, 0xab, 0xd4, 0xe8, 0x37, 0xe9, 0x26, 0xe9, 0x56,
	0x0c, 0xe5, 0x5b, 0x01, 0xe4, 0x31, 0x2a, 0x4f, 0x1d, 0x5c, 0xff, 0x95, 0x16, 0x26, 0xbd, 0xd2,
	0xe7, 0x20, 0x1d, 0x4e, 0x3e, 0x52, 0x22, 0x97, 0xc8, 0x2f, 0x96, 0x8e, 0x8c, 0x5e, 0xab, 0x07,
	0xff, 0x6a, 0x4f, 0xf4, 0xb4, 0xc5, 0x5b, 0x28, 0x3b, 0x87, 0x24, 0xa4, 0xa4, 0x6e, 0x04, 0xd7,
	0xe9, 0x91, 0x9f, 0x78, 0x1e, 0x80, 0x5c, 0x73, 0xa9, 0x47, 0xfc, 0x60, 0x8a, 0x48, 0x3e, 0x70,
	0x8a, 0x08, 0xc4, 0xf2, 0x1d, 0x12, 0xce, 0xa1, 0x70, 0x9a, 0x88, 0x7c, 0xcb, 0x4c, 0xf9, 0x4c,
	0x00, 0x79, 0x4c, 0x29, 0x53, 0xaf, 0x56, 0x19, 0x66, 0xb1, 0x4b, 0xab, 0xc1, 0x23, 0x1c, 0xca,
	0xe7, 0xe9, 0xb1, 0xd0, 0x1c, 0xd2, 0x84, 0x50, 0x69, 0xec, 0xd2, 0x0b, 0xa4, 0x3b, 0x22, 0xc2,
	0xc4, 0x61, 0x44, 0xf8, 0x23, 0x82, 0x63, 0x23, 0x22, 0xdc, 0x8c, 0x75, 0x93, 0xc7, 0x5d, 0x8a,
	0x7f, 0x21, 0x38, 0x3a, 0x2c, 0xc5, 0x38, 0xfa, 0x29, 0x82, 0xaf, 0x3f, 0x8a, 0xb6, 0x3e, 0x7e,
	0xcd, 0x70, 0x6b, 0xff, 0x05, 0xc1, 0xd1, 0x77, 0x1f, 0x87, 0x6c, 0x2f, 0x4d, 0xcc, 0xf6, 0xd9,
	0xf1, 0xc9, 0x75, 0x60, 0x73, 0xe0, 0x9b, 0x65, 0xc3, 0x2a, 0x27, 0xa1, 0x65, 0x0d, 0x8f, 0x38,
	0xd1, 0x3c, 0xb8, 0x3d, 0x29, 0xa3, 0xc4, 0x7f, 0xcf, 0x68, 0x14, 0xbf, 0x76, 0xf1, 0xd7, 0x3f,
	0xe5, 0x99, 0x4f, 0xf7, 0x65, 0xf4, 0xcd, 0xbe, 0x8c, 0xee, 0xed, 0xcb, 0x33, 0x7f, 0xef, 0xcb,
	0xe8, 0xe6, 0x5d, 0x79, 0xe6, 0xa7, 0xbb, 0x32, 0xfa, 0xa0, 0x78, 0x88, 0x29, 0x93, 0xd9, 0x6e,
	0xad, 0x96, 0xe6, 0x1a, 0x3b, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xf8, 0xf6, 0xe7,
	0x1b, 0x0f, 0x00, 0x00,
}

func (this *Application) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Application)
	if !ok {
		that2, ok := that.(Application)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Ids.Equal(that1.Ids) {
		return false
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return false
	}
	if !this.UpdatedAt.Equal(that1.UpdatedAt) {
		return false
	}
	if that1.DeletedAt == nil {
		if this.DeletedAt != nil {
			return false
		}
	} else if !this.DeletedAt.Equal(*that1.DeletedAt) {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if len(this.Attributes) != len(that1.Attributes) {
		return false
	}
	for i := range this.Attributes {
		if this.Attributes[i] != that1.Attributes[i] {
			return false
		}
	}
	if len(this.ContactInfo) != len(that1.ContactInfo) {
		return false
	}
	for i := range this.ContactInfo {
		if !this.ContactInfo[i].Equal(that1.ContactInfo[i]) {
			return false
		}
	}
	if this.DevEuiCounter != that1.DevEuiCounter {
		return false
	}
	return true
}
func (this *Applications) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Applications)
	if !ok {
		that2, ok := that.(Applications)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Applications) != len(that1.Applications) {
		return false
	}
	for i := range this.Applications {
		if !this.Applications[i].Equal(that1.Applications[i]) {
			return false
		}
	}
	return true
}
func (this *IssueDevEUIResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IssueDevEUIResponse)
	if !ok {
		that2, ok := that.(IssueDevEUIResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DevEui.Equal(that1.DevEui) {
		return false
	}
	return true
}
func (this *GetApplicationRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetApplicationRequest)
	if !ok {
		that2, ok := that.(GetApplicationRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if !this.FieldMask.Equal(that1.FieldMask) {
		return false
	}
	return true
}
func (this *ListApplicationsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListApplicationsRequest)
	if !ok {
		that2, ok := that.(ListApplicationsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Collaborator.Equal(that1.Collaborator) {
		return false
	}
	if !this.FieldMask.Equal(that1.FieldMask) {
		return false
	}
	if this.Order != that1.Order {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if this.Page != that1.Page {
		return false
	}
	if this.Deleted != that1.Deleted {
		return false
	}
	return true
}
func (this *CreateApplicationRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateApplicationRequest)
	if !ok {
		that2, ok := that.(CreateApplicationRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Application.Equal(&that1.Application) {
		return false
	}
	if !this.Collaborator.Equal(&that1.Collaborator) {
		return false
	}
	return true
}
func (this *UpdateApplicationRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateApplicationRequest)
	if !ok {
		that2, ok := that.(UpdateApplicationRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Application.Equal(&that1.Application) {
		return false
	}
	if !this.FieldMask.Equal(that1.FieldMask) {
		return false
	}
	return true
}
func (this *ListApplicationAPIKeysRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListApplicationAPIKeysRequest)
	if !ok {
		that2, ok := that.(ListApplicationAPIKeysRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if this.Page != that1.Page {
		return false
	}
	return true
}
func (this *GetApplicationAPIKeyRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetApplicationAPIKeyRequest)
	if !ok {
		that2, ok := that.(GetApplicationAPIKeyRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if this.KeyId != that1.KeyId {
		return false
	}
	return true
}
func (this *CreateApplicationAPIKeyRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateApplicationAPIKeyRequest)
	if !ok {
		that2, ok := that.(CreateApplicationAPIKeyRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Rights) != len(that1.Rights) {
		return false
	}
	for i := range this.Rights {
		if this.Rights[i] != that1.Rights[i] {
			return false
		}
	}
	if that1.ExpiresAt == nil {
		if this.ExpiresAt != nil {
			return false
		}
	} else if !this.ExpiresAt.Equal(*that1.ExpiresAt) {
		return false
	}
	return true
}
func (this *UpdateApplicationAPIKeyRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateApplicationAPIKeyRequest)
	if !ok {
		that2, ok := that.(UpdateApplicationAPIKeyRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if !this.APIKey.Equal(&that1.APIKey) {
		return false
	}
	if !this.FieldMask.Equal(that1.FieldMask) {
		return false
	}
	return true
}
func (this *ListApplicationCollaboratorsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListApplicationCollaboratorsRequest)
	if !ok {
		that2, ok := that.(ListApplicationCollaboratorsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if this.Page != that1.Page {
		return false
	}
	return true
}
func (this *GetApplicationCollaboratorRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetApplicationCollaboratorRequest)
	if !ok {
		that2, ok := that.(GetApplicationCollaboratorRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if !this.Collaborator.Equal(that1.Collaborator) {
		return false
	}
	return true
}
func (this *SetApplicationCollaboratorRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SetApplicationCollaboratorRequest)
	if !ok {
		that2, ok := that.(SetApplicationCollaboratorRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ApplicationIds.Equal(that1.ApplicationIds) {
		return false
	}
	if !this.Collaborator.Equal(that1.Collaborator) {
		return false
	}
	return true
}
func (this *ListAllApplicationsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListAllApplicationsResponse)
	if !ok {
		that2, ok := that.(ListAllApplicationsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.ApplicationIds) != len(that1.ApplicationIds) {
		return false
	}
	for i := range this.ApplicationIds {
		if !this.ApplicationIds[i].Equal(that1.ApplicationIds[i]) {
			return false
		}
	}
	return true
}
func (this *Application) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForContactInfo := "[]*ContactInfo{"
	for _, f := range this.ContactInfo {
		repeatedStringForContactInfo += strings.Replace(fmt.Sprintf("%v", f), "ContactInfo", "ContactInfo", 1) + ","
	}
	repeatedStringForContactInfo += "}"
	keysForAttributes := make([]string, 0, len(this.Attributes))
	for k := range this.Attributes {
		keysForAttributes = append(keysForAttributes, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAttributes)
	mapStringForAttributes := "map[string]string{"
	for _, k := range keysForAttributes {
		mapStringForAttributes += fmt.Sprintf("%v: %v,", k, this.Attributes[k])
	}
	mapStringForAttributes += "}"
	s := strings.Join([]string{`&Application{`,
		`Ids:` + strings.Replace(fmt.Sprintf("%v", this.Ids), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`CreatedAt:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.CreatedAt), "Timestamp", "types.Timestamp", 1), `&`, ``, 1) + `,`,
		`UpdatedAt:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.UpdatedAt), "Timestamp", "types.Timestamp", 1), `&`, ``, 1) + `,`,
		`DeletedAt:` + strings.Replace(fmt.Sprintf("%v", this.DeletedAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`Attributes:` + mapStringForAttributes + `,`,
		`ContactInfo:` + repeatedStringForContactInfo + `,`,
		`DevEuiCounter:` + fmt.Sprintf("%v", this.DevEuiCounter) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Applications) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForApplications := "[]*Application{"
	for _, f := range this.Applications {
		repeatedStringForApplications += strings.Replace(f.String(), "Application", "Application", 1) + ","
	}
	repeatedStringForApplications += "}"
	s := strings.Join([]string{`&Applications{`,
		`Applications:` + repeatedStringForApplications + `,`,
		`}`,
	}, "")
	return s
}
func (this *IssueDevEUIResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&IssueDevEUIResponse{`,
		`DevEui:` + fmt.Sprintf("%v", this.DevEui) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetApplicationRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetApplicationRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`FieldMask:` + strings.Replace(fmt.Sprintf("%v", this.FieldMask), "FieldMask", "types.FieldMask", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListApplicationsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListApplicationsRequest{`,
		`Collaborator:` + strings.Replace(fmt.Sprintf("%v", this.Collaborator), "OrganizationOrUserIdentifiers", "OrganizationOrUserIdentifiers", 1) + `,`,
		`FieldMask:` + strings.Replace(fmt.Sprintf("%v", this.FieldMask), "FieldMask", "types.FieldMask", 1) + `,`,
		`Order:` + fmt.Sprintf("%v", this.Order) + `,`,
		`Limit:` + fmt.Sprintf("%v", this.Limit) + `,`,
		`Page:` + fmt.Sprintf("%v", this.Page) + `,`,
		`Deleted:` + fmt.Sprintf("%v", this.Deleted) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateApplicationRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateApplicationRequest{`,
		`Application:` + strings.Replace(strings.Replace(this.Application.String(), "Application", "Application", 1), `&`, ``, 1) + `,`,
		`Collaborator:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Collaborator), "OrganizationOrUserIdentifiers", "OrganizationOrUserIdentifiers", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateApplicationRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateApplicationRequest{`,
		`Application:` + strings.Replace(strings.Replace(this.Application.String(), "Application", "Application", 1), `&`, ``, 1) + `,`,
		`FieldMask:` + strings.Replace(fmt.Sprintf("%v", this.FieldMask), "FieldMask", "types.FieldMask", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListApplicationAPIKeysRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListApplicationAPIKeysRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`Limit:` + fmt.Sprintf("%v", this.Limit) + `,`,
		`Page:` + fmt.Sprintf("%v", this.Page) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetApplicationAPIKeyRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetApplicationAPIKeyRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`KeyId:` + fmt.Sprintf("%v", this.KeyId) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateApplicationAPIKeyRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateApplicationAPIKeyRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Rights:` + fmt.Sprintf("%v", this.Rights) + `,`,
		`ExpiresAt:` + strings.Replace(fmt.Sprintf("%v", this.ExpiresAt), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateApplicationAPIKeyRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateApplicationAPIKeyRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`APIKey:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.APIKey), "APIKey", "APIKey", 1), `&`, ``, 1) + `,`,
		`FieldMask:` + strings.Replace(fmt.Sprintf("%v", this.FieldMask), "FieldMask", "types.FieldMask", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListApplicationCollaboratorsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListApplicationCollaboratorsRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`Limit:` + fmt.Sprintf("%v", this.Limit) + `,`,
		`Page:` + fmt.Sprintf("%v", this.Page) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetApplicationCollaboratorRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetApplicationCollaboratorRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`Collaborator:` + strings.Replace(fmt.Sprintf("%v", this.Collaborator), "OrganizationOrUserIdentifiers", "OrganizationOrUserIdentifiers", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SetApplicationCollaboratorRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SetApplicationCollaboratorRequest{`,
		`ApplicationIds:` + strings.Replace(fmt.Sprintf("%v", this.ApplicationIds), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + `,`,
		`Collaborator:` + strings.Replace(fmt.Sprintf("%v", this.Collaborator), "Collaborator", "Collaborator", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListAllApplicationsResponse) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForApplicationIds := "[]*ApplicationIdentifiers{"
	for _, f := range this.ApplicationIds {
		repeatedStringForApplicationIds += strings.Replace(fmt.Sprintf("%v", f), "ApplicationIdentifiers", "ApplicationIdentifiers", 1) + ","
	}
	repeatedStringForApplicationIds += "}"
	s := strings.Join([]string{`&ListAllApplicationsResponse{`,
		`ApplicationIds:` + repeatedStringForApplicationIds + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringApplication(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
